macro(have_framework_target project_root_path)
  if(TARGET vstream_core)
    set(HAVE_FRAMEWORK_TARGET TRUE)
  else()
    if(NOT EXISTS ${project_root_path}/lib/libvstream_core.so)
      message(FATAL_ERROR "Build framework first")
    endif()
    link_directories(${project_root_path}/lib)
  endif()
  include_directories(${project_root_path}/framework/core/include)
  if (NOT DEFINED VSTREAM_LIB_PATH)
    set(VSTREAM_LIB_PATH ${project_root_path}/lib PARENT_SCOPE)
  endif()
endmacro()


macro(have_modules_target project_root_path)
  if(TARGET vstream_va)
    set(HAVE_MODULES_TARGET TRUE)
  else()
    if(NOT EXISTS ${project_root_path}/lib/libvstream_va.so)
      message(FATAL_ERROR "Build modules first")
    endif()
    link_directories(${project_root_path}/lib)
  endif()
  if (NOT DEFINED VSTREAM_LIB_PATH)
    set(VSTREAM_LIB_PATH ${project_root_path}/lib PARENT_SCOPE)
  endif()
endmacro()

macro(have_modules_contrib_target project_root_path)
  if(TARGET vstream_contrib)
    set(HAVE_MODULES_CONTRIB_TARGET TRUE)
    set(HAVE_MODULES_CONTRIB TRUE)
  else()
    if(EXISTS ${project_root_path}/lib/libvstream_contrib.so)
      set(HAVE_MODULES_CONTRIB TRUE)
      link_directories(${project_root_path}/lib)
    endif()
  endif()
  if (NOT DEFINED VSTREAM_LIB_PATH)
    set(VSTREAM_LIB_PATH ${project_root_path}/lib PARENT_SCOPE)
  endif()
endmacro()
