macro(have_framework_target modelstream_root_path)
  if(TARGET modelstream_core)
    set(HAVE_FRAMEWORK_TARGET TRUE)
  else()
    if(NOT EXISTS ${modelstream_root_path}/lib/libmodelstream_core.so)
      message(FATAL_ERROR "Build framework first")
    endif()
    link_directories(${modelstream_root_path}/lib)
  endif()
  include_directories(${modelstream_root_path}/framework/core/include)
  if (NOT DEFINED MODELSTREAM_LIB_PATH)
    set(MODELSTREAM_LIB_PATH ${modelstream_root_path}/lib PARENT_SCOPE)
  endif()
endmacro()


macro(have_modules_target modelstream_root_path)
  if(TARGET modelstream_va)
    set(HAVE_MODULES_TARGET TRUE)
  else()
    if(NOT EXISTS ${modelstream_root_path}/lib/libmodelstream_va.so)
      message(FATAL_ERROR "Build modules first")
    endif()
    link_directories(${modelstream_root_path}/lib)
  endif()
  if (NOT DEFINED MODELSTREAM_LIB_PATH)
    set(MODELSTREAM_LIB_PATH ${modelstream_root_path}/lib PARENT_SCOPE)
  endif()
endmacro()

macro(have_modules_contrib_target modelstream_root_path)
  if(TARGET modelstream_contrib)
    set(HAVE_MODULES_CONTRIB_TARGET TRUE)
    set(HAVE_MODULES_CONTRIB TRUE)
  else()
    if(EXISTS ${modelstream_root_path}/lib/libmodelstream_contrib.so)
      set(HAVE_MODULES_CONTRIB TRUE)
      link_directories(${modelstream_root_path}/lib)
    endif()
  endif()
  if (NOT DEFINED MODELSTREAM_LIB_PATH)
    set(MODELSTREAM_LIB_PATH ${modelstream_root_path}/lib PARENT_SCOPE)
  endif()
endmacro()
